services:
  server:
    build: ./server
    ports:
      - '5001:5001'
    volumes:
      - ./server:/usr/src/app
    env_file: ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - '3000:80'
    volumes:
      - ./client:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - server

  db:
    image: mongo:6
    restart: always
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
